indieweb_cache.settings:
  type: config_object
  label: 'Indieweb cache'
  mapping:
    enable:
      type: boolean
      label: 'Enable caching of media'
    use_imagecache_external:
      type: boolean
      label: 'Use external imagecache module'
    image_style_avatar:
      type: string
      label: 'The image style to apply to the downloaded image for an avatar'
    image_style_photo:
      type: string
      label: 'The image style to apply to the downloaded image for any other photo'
    protect_webmention_avatar_from_flush:
      type: boolean
      label: 'Protect webmention avatars from flush'
    protect_webmention_image_from_flush:
      type: boolean
      label: 'Protect webmention images from flush'
    protect_post_context_image_from_flush:
      type: boolean
      label: 'Protect post context images from flush'
    protect_contact_image_from_flush:
      type: boolean
      label: 'Protect contact images from flush'
    ignore_webmention_io:
      type: boolean
      label: 'Ignore webmention.io'
