block.settings.indieweb_webmention:
  type: block_settings
  label: 'Webmentions block'
  mapping:
    show_likes:
      type: boolean
      label: 'Show likes'
    show_reposts:
      type: boolean
      label: 'Show reposts'
    show_replies:
      type: boolean
      label: 'Show replies'
    show_mentions:
      type: boolean
      label: 'Show mentions'
    show_bookmarks:
      type: boolean
      label: 'Show bookmarks'
    show_avatar:
      type: boolean
      label: 'Show avatar'
    show_created:
      type: boolean
      label: 'Show created'
    number_of_posts:
      type: integer
      label: 'Number of posts in block'
    sort_field:
      type: string
      label: 'Field to sort by'
    sort_direction:
      type: string
      label: 'Direction to sort by'
    detect_identical:
      type: boolean
      label: 'Whether to detect identical mentions by author and type'

block.settings.indieweb_rsvp:
  type: block_settings
  label: 'RSVP block'
  mapping:
    show_avatar:
      type: boolean
      label: 'Show avatar'
    allow_user_rsvp:
      type: boolean
      label: 'Allow user to RSVP'
    node_type:
      type: string
      label: 'Event node type'
    node_daterange_field:
      type: string
      label: 'Event date range field'
