# schema for indieweb_contact.settings
indieweb_contact.settings:
  type: config_object
  label: 'Indieweb contacts'
  mapping:
    create_on_webmention:
      type: boolean
      label: 'Create contact when a webmention is received'
